version: '3'

services:
  lsnote:
    build: .
    container_name: lsnote
    ports:
      - "80:80"      # 前端端口
      - "8000:8000"  # 后端端口
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=server.settings
      - SECRET_KEY=ls4afcZy1EZwKIqZ61uV3Nhp1RInSTKZYiVXm5IzF
      - AI_API_KEY=your_api_key_here
    volumes:
      - ./data/:/app/data/  # 数据库文件持久化
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/auth/health/?format=json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  nginx:
    image: nginx:alpine
    container_name: lsnote-nginx
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/dist:/usr/share/nginx/html
    depends_on:
      - lsnote
    restart: always 
 
 