version: '3'

services:
  lsnote:
    build: .
    container_name: lsnote
    ports:
      - "8081:80"      # 前端端口
      - "8000:8000"  # 后端端口
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=server.settings
      # 警告：生产环境中，请替换以下敏感值为你自己的安全密钥和API密钥
      # 推荐使用环境文件（.env）管理这些密钥，并确保不要提交到版本控制
      - SECRET_KEY=ls4afcZy1EZwKIqZ61uV3Nhp1RInSTKZYiVXm5IzF  # 请替换为自己的密钥
      - AI_API_KEY=your_api_key_here  # 请替换为你的AI API密钥
      - DB_PATH=/app/data
    volumes:
      - lsnote_data:/app/data/  # 使用命名卷而不是挂载本地目录
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/auth/health/?format=json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  nginx:
    image: nginx:alpine
    container_name: lsnote-nginx
    ports:
      - "8080:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/dist:/usr/share/nginx/html
    depends_on:
      - lsnote
    restart: always

# 定义命名卷
volumes:
  lsnote_data:
    # 这将创建一个Docker管理的命名卷，与本地文件系统隔离
 
 