# Generated by Django 5.1.7 on 2025-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='ai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AI API密钥'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='ai_base_url',
            field=models.CharField(default='https://api.deepseek.com', max_length=255, verbose_name='AI API基础URL'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='ai_model',
            field=models.CharField(default='deepseek-chat', max_length=100, verbose_name='AI模型名称'),
        ),
    ]
