# Generated by Django 5.1.7 on 2025-05-25 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_userpreference_ai_api_key_userpreference_ai_base_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('permission', models.CharField(choices=[('read', '只读'), ('write', '读写'), ('admin', '管理员')], default='read', max_length=10, verbose_name='默认权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '权限模板',
                'verbose_name_plural': '权限模板',
            },
        ),
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='note.notegroup', verbose_name='分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '分组历史',
                'verbose_name_plural': '分组历史',
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
