# Generated by Django 5.1.7 on 2025-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_grouppermissiontemplate_grouphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='conversation_type',
            field=models.CharField(choices=[('chat', '聊天'), ('summary', '摘要'), ('qa', '问答'), ('analysis', '分析'), ('other', '其他')], default='chat', max_length=20, verbose_name='对话类型'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='title',
            field=models.CharField(default='新对话', max_length=100, verbose_name='标题'),
        ),
    ]
