# Generated by Django 5.1.7 on 2025-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_aiconversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='enable_fim',
            field=models.BooleanField(default=False, verbose_name='启用FIM补全'),
        ),
    ]
